# This is a basic workflow to help you get started with Actions

name: Bootcamp-demo-app
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:aamirpinger/bootcamp-2020/blob/master/src/App.js
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: setup node.js enviroment
        uses: actions/setup-node.js@v2-beta
        with:--
          version: 12
      # Runs a set of commands using the runners shell
      - name: Git actions for yarn
        uses: Borales/actions-yarn@v2.1.0
        with:
          #yarn commend
          cmd: install #npm install/yarn install
          
      - name: creating build
        run: sudo yarn build
         
      - name: installing surge
        run: npm install -g surge
        
      -name: doploy on surge
       run: surge ./build http://zdemo-app.surge.sh/ --token ${{ secrets.REACT_APP }}
